export const contactObj = {
  id: "Contact Us",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Contact Us",
  headLine: "Yayasan Endang Saefuddin Anshari",
  description: "Saran dan kritik sangat diapresiasi untuk kemajuan YAPESA",
  buttonLabel: "Go to profile",
  imgStart: false,
  img: require("../../images/YAPESA.jpg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  to: "/profile",
};
