export const homeObjYT = {
  id: "gallery",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Gallery",
  headLine: "Dokumentasi Kegiatan",
  description:
    "Tim YAPESA melakukan kegiatan sosial dan kajian dengan masyarakat sekitar.",
  buttonLabel: "Go to gallery",
  buttonLabel2: "Go to Youtube",
  imgStart: false,
  img: require("../../images/gallery.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
  to: "/gallery",
  url: "https://www.youtube.com/@yapesakampungquran957",
};
