export const kajianObj = {
  id: "kajian-islami",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "kajian Islami",
  headLine: "Kajian Islami YAPESA",
  description:
    "Kajian Islam yang meliputi ibadah Mahdhah dan Ghairu Mahdhah berdasarkan Qur'an dan hadist.",
  buttonLabel: "Go to profile",
  imgStart: false,
  img: require("../../images/kajiantausiah.jpeg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  jadwalText: true,
  jadwal: "Setiap pekan ke 4",
  bright: true,
  to: "/profile",
};
export const jumatBerkahObj = {
  id: "jumat-berkah",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Kegiatan Sosial",
  headLine: "Jum'at Berkah YAPESA",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: true,
  img: require("../../images/jumatberkah.jpeg"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
  jadwalText: false,
  jadwal: "Setiap Jum'at subuh atau siang",
  bright: false,
  to: "/profile",
};
export const tahsinObj = {
  id: "tashin",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Tahsin & Tahfidz",
  headLine: "Kajian Tahsin YAPESA",
  description:
    "Mempelajari dan membaguskan baca'an Al-Qur'an yang benar dan tepat sesuai dengan hukum Tajwid.",
  buttonLabel: "Go to profile",
  imgStart: false,
  img: require("../../images/tahsinyapesa.jpeg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  jadwalText: true,
  jadwal: "Setiap Ahad jam 16.00-17.30",
  bright: true,
  to: "/profile",
};
export const tahfidzOnlineObj = {
  id: "tahfidz-online",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Tahsin & Tahfidz",
  headLine: "Tahfidz Online YAPESA",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: true,
  img: require("../../images/tahfidz.png"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
  jadwalText: false,
  jadwal: "Setiap Rabu 20.00-21.00",
  bright: false,
  to: "/profile",
};

export const tahfidzObj = {
  id: "tahfidz",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Tahsin & Tahfidz",
  headLine: "Tahfidz YAPESA",
  description:
    "Belajar menghafal Al-Qur'an dan setoran hafalan dengan metode Talqin dan Talaqqi.",
  buttonLabel: "Go to profile",
  imgStart: false,
  img: require("../../images/kajian.jpeg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  jadwalText: true,
  jadwal: "Setiap Kamis & Sabtu 16.00-17.30",
  bright: true,
  to: "/profile",
};
