export const kegiatanObjOne = {
  id: "profile-singkat",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Profil Singkat",
  headLine: "Yayasan Endang Saefuddin Anshari",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: false,
  img: require("../../images/YAPESA.jpg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  to: "/profile",
};
export const kegiatanObjTwo = {
  id: "profile-singkat",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Profil Singkat",
  headLine: "Yayasan Endang Saefuddin Anshari",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: true,
  img: require("../../images/YAPESA.jpg"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
  to: "/profile",
};
export const kegiatanObjThree = {
  id: "profile-singkat",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Profil Singkat",
  headLine: "Yayasan Endang Saefuddin Anshari",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: false,
  img: require("../../images/YAPESA.jpg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  to: "/profile",
};
export const kegiatanObjFour = {
  id: "profile-singkat",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Profil Singkat",
  headLine: "Yayasan Endang Saefuddin Anshari",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: false,
  img: require("../../images/YAPESA.jpg"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
  to: "/profile",
};
