export const kegiatanObjOne = {
  id: "kajian-islami",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "kajian Islami",
  headLine: "Kajian Islami YAPESA",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: false,
  img: require("../../images/kajiantausiah.jpeg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  to: "/profile",
};
export const kegiatanObjTwo = {
  id: "jumat-berkah",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Kegiatan Sosial",
  headLine: "Jum'at Berkah YAPESA",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: true,
  img: require("../../images/jumatberkah.jpeg"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
  to: "/profile",
};
export const kegiatanObjThree = {
  id: "tashin-tahfidz",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Tahsin & Tahfidz",
  headLine: "Tahsin dan Tahfidz YAPESA",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: false,
  img: require("../../images/tahsintahfidz.jpeg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  to: "/profile",
};
export const kegiatanObjFour = {
  id: "tahfidz-online",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Tahsin & Tahfidz",
  headLine: "Tahfidz Online YAPESA",
  description:
    "Adalah sebuah lembaga sosial yang terletak di Jl. Platina No 15, Komplek Logam, Buahbatu Bandung yang saat ini sedang dalam proses menjadi madrasah yang maju dan moderen.",
  buttonLabel: "Go to profile",
  imgStart: true,
  img: require("../../images/tahfidz.png"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
  to: "/profile",
};
